name: Test, Build & Deploy App

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v5

      - name: Build Docker Image
        run: docker build -t ${{ secrets.REPO_NAME }}:latest .

      - name: Use hash of commit
        run: docker tag ${{ secrets.REPO_NAME }}:latest ${{ secrets.REPO_NAME }}:${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to AWS
        run: |
          docker push ${{ secrets.REPO_NAME }}:latest
          docker push ${{ secrets.REPO_NAME }}:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/containers
            docker pull ${{ secrets.REPO_NAME }}:latest
            docker compose up -d